### ISSUE TITLE
Init issue on JSReport server

### ISSUE THREAD

**Issue by ychhajed** [jsreport/jsreport-version-control#2]
We have a standalone jsreport server running in elastic beanstalk. We want to add support for version control on this server(Preferably using Git). We included the "jsreport-version-control" module in the package.json and also added the below code in start.js.

```
require('jsreport')().init();
var jsreportcore = require('jsreport-core')();
jsreportcore.use(require('jsreport-version-control')());
```

When we run the app it gives error 

```
node_modules/jsreport-version-control/lib/versionControl.js:181
          ...change,
          ^^^

SyntaxError: Unexpected token ...
```

Our JsReport server version is 1.3.1. 

Do we need to upgrade to the latest version of JSReport server to use version control or it is missing some configuration settings ?

Thanks.

**Comment by bjrmatos** [comment]
hi!



> require('jsreport')().init();
> var jsreportcore = require('jsreport-core')();
> jsreportcore.use(require('jsreport-version-control')());

are you using both jsreport and jsreport-core at the same time? do you have any reason for that?



> When we run the app it gives error
> 
> node_modules/jsreport-version-control/lib/versionControl.js:181
>           ...change,
>           ^^^
> 
> SyntaxError: Unexpected token ...

what version of node are you using? [jsreport-version-control is compatible with node >=8](https://github.com/jsreport/jsreport-version-control/blob/master/package.json#L28), that error means that you are using lower node version where some syntax is not supported. you should be fine if you find a way to upgrade the node version that your app is using.



> Our JsReport server version is 1.3.1.
> 
> Do we need to upgrade to the latest version of JSReport server to use version control or it is missing some configuration settings ?

since it seems that you are using the two packages (jsreport and jsreport-core) i'm not sure about which version correspond to the package that you have. is it jsreport or jsreport-core? i'm not 100% sure but since jsreport-version-control is something new it should be possible to use it at that version, and if for some reason it is not possible to use it in that old version you should probably upgrade to the latest jsreport version. but first, remember to upgrade your node version to >=8.

**Comment by ychhajed** [comment]
We are using jsreport only. So I changed the code in start.js to use jsreport only but still see the same error.
```
var jsreport = require('jsreport')();
jsreport.init();
jsreport.use(require('jsreport-version-control')());
```

Node version is 8.1.3

We are using only one package jsreport. Here is the package.json code :
```
{
  "name": "jsreport-server",
  "scripts": {
    "start": "node start.js"
  },
  "dependencies": {
    "dateformat": "*",
    "jsreport": "1.3.1",
    "jsreport-mongodb-store": "*",
    "jsreport-version-control": "^0.2.0",
    "mongodb": "*",
    "request": "*"
  },
  "main": "server.js"
}
```

**Comment by pofider** [comment]
Closing. The package.json manifest now requires node version >=8.9.0
